version: '3.1'

services:
    sf2:
        container_name: "SF2_cfs"
        restart: on-failure
        user: "1000:1000"
        environment:
            DOCKER_HOST_PROJECT_DIR: "${PWD}"
            DOCKER_CONTAINER_PROJECT_DIR: "/opt/cfs"
            O: "build-SF2"
            SIMULATION: "cortex-m3"
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            MISSIONCONFIG: "SF2"
            LINKER_SCRIPT: "/opt/cfs/ld/production-smartfusion2-execute-in-place.ld"
        build:
            context: ./dockerfiles
            dockerfile: ubuntu18
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "2"
        volumes:
            - ".:/opt/cfs"
